"""initial

Revision ID: 9e18d0fc1759
Revises:
Create Date: 2026-04-25 20:34:29.944015

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e18d0fc1759"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personas",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tiktok_account_id", sa.String(), nullable=False),
        sa.Column("style", sa.String(), nullable=True),
        sa.Column("tone", sa.String(), nullable=True),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("voice_speaker", sa.String(), nullable=True),
        sa.Column("voice_speaker_wav", sa.String(), nullable=True),
        sa.Column("show_captions", sa.Boolean(), nullable=False),
        sa.Column("real_news_ratio", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("source_article_url", sa.String(), nullable=True),
        sa.Column("source_article_title", sa.String(), nullable=True),
        sa.Column("base_script", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "persona_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("persona_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("narration", sa.String(), nullable=True),
        sa.Column("tiktok_caption", sa.String(), nullable=True),
        sa.Column("audio_path", sa.String(), nullable=True),
        sa.Column("video_category", sa.String(), nullable=True),
        sa.Column("background_video_path", sa.String(), nullable=True),
        sa.Column("output_video_path", sa.String(), nullable=True),
        sa.Column("tiktok_post_id", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("persona_runs")
    op.drop_table("runs")
    op.drop_table("personas")
    # ### end Alembic commands ###
